version: "3.9"

services:
  web:
    build: .
    image: observapvh
    container_name: observapvh
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py seed_data &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - rede_proxy
    ports:
      - "8000:8000"

