# Generated by Django 5.1.15 on 2026-08-09 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('icone', models.CharField(blank=True, help_text='Emoji representativo exibido no card.', max_length=8, verbose_name='ícone (emoji)')),
                ('cor', models.CharField(default='#2E7D32', help_text='Cor de destaque em CSS, ex: #2E7D32', max_length=7, verbose_name='cor (hex)')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'Bioma',
                'verbose_name_plural': 'Biomas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=60, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='slug')),
                ('cor', models.CharField(default='#2E7D32', max_length=7, verbose_name='cor (hex)')),
            ],
            options={
                'verbose_name': 'Categoria de notícia',
                'verbose_name_plural': 'Categorias de notícia',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='slug')),
                ('ano_inicio', models.PositiveSmallIntegerField(verbose_name='ano inicial')),
                ('ano_fim', models.PositiveSmallIntegerField(verbose_name='ano final')),
                ('resumo', models.TextField(blank=True, verbose_name='resumo')),
                ('lancado_em', models.DateField(blank=True, null=True, verbose_name='lançado em')),
                ('destaque', models.BooleanField(default=False, verbose_name='destaque')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'Coleção',
                'verbose_name_plural': 'Coleções',
                'ordering': ['-lancado_em', '-ano_fim'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('categoria', models.CharField(blank=True, max_length=80, verbose_name='categoria')),
                ('pergunta', models.CharField(max_length=250, verbose_name='pergunta')),
                ('resposta', models.TextField(verbose_name='resposta')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'Pergunta Frequente',
                'verbose_name_plural': 'Perguntas Frequentes',
                'ordering': ['ordem', 'pergunta'],
            },
        ),
        migrations.CreateModel(
            name='MensagemContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('assunto', models.CharField(max_length=200, verbose_name='assunto')),
                ('mensagem', models.TextField(verbose_name='mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='lida')),
            ],
            options={
                'verbose_name': 'Mensagem de contato',
                'verbose_name_plural': 'Mensagens de contato',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('site', models.URLField(blank=True, verbose_name='site')),
                ('tipo', models.CharField(blank=True, help_text='ex: universidade, ONG, empresa de tecnologia', max_length=40, verbose_name='tipo')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='parceiros/', verbose_name='logo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Pilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(max_length=120, verbose_name='título')),
                ('icone', models.CharField(blank=True, max_length=8, verbose_name='ícone (emoji)')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'Pilar',
                'verbose_name_plural': 'Pilares',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='TermoGlossario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('termo', models.CharField(max_length=80, unique=True, verbose_name='termo')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug')),
                ('definicao', models.TextField(verbose_name='definição')),
                ('categoria', models.CharField(blank=True, max_length=80, verbose_name='categoria')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'Termo do glossário',
                'verbose_name_plural': 'Termos do glossário',
                'ordering': ['termo'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('resumo', models.TextField(blank=True, max_length=400, verbose_name='resumo')),
                ('conteudo', models.TextField(verbose_name='conteúdo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='imagem de capa')),
                ('publicado_em', models.DateTimeField(blank=True, null=True, verbose_name='publicado em')),
                ('destaque', models.BooleanField(default=False, verbose_name='destaque na home')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='core.categorianoticia', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-publicado_em', '-criado_em'],
            },
        ),
    ]
