# Generated by Django 5.1.15 on 2026-08-09 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(max_length=120, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='slug')),
                ('descricao_curta', models.CharField(blank=True, help_text='Até 200 caracteres — exibida nos cards.', max_length=200, verbose_name='descrição curta')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição completa')),
                ('icone', models.CharField(blank=True, help_text='Ex: bi-droplet, bi-tree, bi-cloud-rain', max_length=40, verbose_name='ícone (Bootstrap Icons name)')),
                ('cor', models.CharField(default='#0d3b66', max_length=7, verbose_name='cor (hex)')),
                ('coordenador', models.CharField(blank=True, max_length=120, verbose_name='coordenador(a)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'Grupo de Trabalho',
                'verbose_name_plural': 'Grupos de Trabalho',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='slug')),
                ('funcao', models.CharField(blank=True, max_length=120, verbose_name='função / cargo')),
                ('instituicao', models.CharField(blank=True, max_length=180, verbose_name='instituição')),
                ('biografia', models.TextField(blank=True, verbose_name='biografia')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='membros/', verbose_name='foto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('link_lattes', models.URLField(blank=True, verbose_name='Lattes')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug')),
                ('icone', models.CharField(default='bi-file-earmark-text', max_length=40, verbose_name='ícone (Bootstrap Icons)')),
                ('cor', models.CharField(default='#0d3b66', max_length=7, verbose_name='cor (hex)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'Tipo de publicação',
                'verbose_name_plural': 'Tipos de publicação',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='bioma',
            name='cor',
            field=models.CharField(default='#1d4e89', help_text='Cor de destaque em CSS, ex: #1d4e89', max_length=7, verbose_name='cor (hex)'),
        ),
        migrations.AlterField(
            model_name='categorianoticia',
            name='cor',
            field=models.CharField(default='#0d3b66', max_length=7, verbose_name='cor (hex)'),
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(max_length=220, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True, verbose_name='slug')),
                ('resumo', models.TextField(blank=True, verbose_name='resumo')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição completa')),
                ('autores', models.CharField(blank=True, max_length=300, verbose_name='autores')),
                ('publicado_em', models.DateField(blank=True, null=True, verbose_name='data')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='publicacoes/', verbose_name='arquivo (PDF)')),
                ('link_externo', models.URLField(blank=True, verbose_name='link externo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='publicacoes/capas/', verbose_name='imagem de capa')),
                ('destaque', models.BooleanField(default=False, verbose_name='destaque na home')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicacoes', to='core.tipopublicacao', verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
                'ordering': ['-publicado_em', '-criado_em'],
            },
        ),
    ]
