# Generated by Django 4.2.11 on 2026-08-29 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_grupotrabalho_membro_tipopublicacao_alter_bioma_cor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('icone', models.CharField(blank=True, default='bi-map', max_length=40, verbose_name='ícone (Bootstrap Icons)')),
                ('cor', models.CharField(default='#0d3b66', max_length=7, verbose_name='cor (hex)')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'Região',
                'verbose_name_plural': 'Regiões',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug')),
                ('codigo_ibge', models.CharField(blank=True, max_length=20, verbose_name='código IBGE')),
                ('tipo', models.CharField(default='Distrito', max_length=40, verbose_name='tipo')),
                ('populacao', models.PositiveIntegerField(blank=True, null=True, verbose_name='população')),
                ('domicilios', models.PositiveIntegerField(blank=True, null=True, verbose_name='domicílios')),
                ('area_km2', models.FloatField(blank=True, null=True, verbose_name='área (km²)')),
                ('densidade', models.FloatField(blank=True, null=True, verbose_name='densidade demográfica (hab/km²)')),
                ('criacao', models.CharField(blank=True, max_length=60, verbose_name='data/ano de criação')),
                ('distancia_sede_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='distância da sede (km)')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags / palavras-chave')),
                ('icone', models.CharField(blank=True, default='bi-geo-alt', max_length=40, verbose_name='ícone (emoji ou BI)')),
                ('cor', models.CharField(default='#1d4e89', max_length=7, verbose_name='cor (hex)')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('regiao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distritos', to='core.regiao', verbose_name='região')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'ordering': ['-populacao', 'nome'],
            },
        ),
    ]
