# Generated by Django 5.1.15 on 2026-09-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='link_responsivo',
            field=models.URLField(blank=True, default='', help_text='URL pública do dashboard para Mobile (ex: https://painel.provaconceito.tech/superset/dashboard/.../?standalone=2&show_filters=0). Se não preenchida, é gerada automaticamente no salvar.', max_length=500, verbose_name='link / URL do iframe (Mobile)'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='link',
            field=models.URLField(help_text='URL pública do dashboard para Desktop, ex: https://painel.provaconceito.tech/superset/dashboard/.../?standalone=2', max_length=500, verbose_name='link / URL do iframe (Desktop)'),
        ),
    ]
