# Generated by Django 5.1.15 on 2026-09-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dashboard_link_responsivo_alter_dashboard_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacaoRedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(help_text='Título descritivo ou assunto principal da postagem.', max_length=200, verbose_name='título / assunto')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('rede_social', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('twitter', 'X (Twitter)'), ('outra', 'Outra')], default='instagram', max_length=20, verbose_name='rede social')),
                ('perfil', models.CharField(default='observa.pvh', help_text='Nome do perfil nas redes (ex: observa.pvh)', max_length=100, verbose_name='perfil / conta')),
                ('legenda', models.TextField(help_text='Legenda completa da publicação nas mídias sociais.', verbose_name='legenda da publicação')),
                ('imagem', models.ImageField(blank=True, help_text='Upload da imagem ou card da postagem.', null=True, upload_to='redes_sociais/', verbose_name='imagem do post')),
                ('imagem_url', models.URLField(blank=True, help_text='Link de imagem externa caso não envie arquivo.', verbose_name='URL da imagem (opcional)')),
                ('link_postagem', models.URLField(help_text='URL direta para o post no Instagram ou Facebook.', verbose_name='link direto da publicação')),
                ('publicado_em', models.DateTimeField(blank=True, null=True, verbose_name='publicado em')),
                ('curtidas_texto', models.CharField(blank=True, default='Curtido por outras pessoas', help_text='ex: Curtido por denilsonsconde e outras 45 pessoas', max_length=150, verbose_name='texto de interações/curtidas')),
                ('destaque', models.BooleanField(default=False, verbose_name='destaque na home')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'Divulgação Popular (Rede Social)',
                'verbose_name_plural': 'Divulgação Popular (Mídias Sociais)',
                'ordering': ['-publicado_em', '-criado_em'],
            },
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='link',
            field=models.URLField(help_text='URL pública do dashboard para Desktop, ex: https://painel.provaconceito.tech/superset/dashboard/.../?standalone=1', max_length=500, verbose_name='link / URL do iframe (Desktop)'),
        ),
    ]
